/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTicketsRouteImport } from './routes/_authenticated/tickets'
import { Route as AuthenticatedTechRouteImport } from './routes/_authenticated/tech'
import { Route as AuthenticatedSoftwareRouteImport } from './routes/_authenticated/software'
import { Route as AuthenticatedServersRouteImport } from './routes/_authenticated/servers'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPmRouteImport } from './routes/_authenticated/pm'
import { Route as AuthenticatedNetworkRouteImport } from './routes/_authenticated/network'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAssetsRouteImport } from './routes/_authenticated/assets'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedBriefingsIndexRouteImport } from './routes/_authenticated/briefings.index'
import { Route as AuthenticatedBriefingsIdRouteImport } from './routes/_authenticated/briefings.$id'
import { Route as AuthenticatedAdminActiveDirectoryRouteImport } from './routes/_authenticated/admin.active-directory'
import { Route as ApiPublicHooksPmRemindersRouteImport } from './routes/api/public/hooks/pm-reminders'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTicketsRoute = AuthenticatedTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTechRoute = AuthenticatedTechRouteImport.update({
  id: '/tech',
  path: '/tech',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSoftwareRoute = AuthenticatedSoftwareRouteImport.update({
  id: '/software',
  path: '/software',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServersRoute = AuthenticatedServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPmRoute = AuthenticatedPmRouteImport.update({
  id: '/pm',
  path: '/pm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNetworkRoute = AuthenticatedNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssetsRoute = AuthenticatedAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBriefingsIndexRoute =
  AuthenticatedBriefingsIndexRouteImport.update({
    id: '/briefings/',
    path: '/briefings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBriefingsIdRoute =
  AuthenticatedBriefingsIdRouteImport.update({
    id: '/briefings/$id',
    path: '/briefings/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminActiveDirectoryRoute =
  AuthenticatedAdminActiveDirectoryRouteImport.update({
    id: '/admin/active-directory',
    path: '/admin/active-directory',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksPmRemindersRoute =
  ApiPublicHooksPmRemindersRouteImport.update({
    id: '/api/public/hooks/pm-reminders',
    path: '/api/public/hooks/pm-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/assets': typeof AuthenticatedAssetsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/network': typeof AuthenticatedNetworkRoute
  '/pm': typeof AuthenticatedPmRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/servers': typeof AuthenticatedServersRoute
  '/software': typeof AuthenticatedSoftwareRoute
  '/tech': typeof AuthenticatedTechRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/admin/active-directory': typeof AuthenticatedAdminActiveDirectoryRoute
  '/briefings/$id': typeof AuthenticatedBriefingsIdRoute
  '/briefings/': typeof AuthenticatedBriefingsIndexRoute
  '/api/public/hooks/pm-reminders': typeof ApiPublicHooksPmRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/assets': typeof AuthenticatedAssetsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/network': typeof AuthenticatedNetworkRoute
  '/pm': typeof AuthenticatedPmRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/servers': typeof AuthenticatedServersRoute
  '/software': typeof AuthenticatedSoftwareRoute
  '/tech': typeof AuthenticatedTechRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/admin/active-directory': typeof AuthenticatedAdminActiveDirectoryRoute
  '/briefings/$id': typeof AuthenticatedBriefingsIdRoute
  '/briefings': typeof AuthenticatedBriefingsIndexRoute
  '/api/public/hooks/pm-reminders': typeof ApiPublicHooksPmRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/assets': typeof AuthenticatedAssetsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/network': typeof AuthenticatedNetworkRoute
  '/_authenticated/pm': typeof AuthenticatedPmRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/servers': typeof AuthenticatedServersRoute
  '/_authenticated/software': typeof AuthenticatedSoftwareRoute
  '/_authenticated/tech': typeof AuthenticatedTechRoute
  '/_authenticated/tickets': typeof AuthenticatedTicketsRoute
  '/_authenticated/admin/active-directory': typeof AuthenticatedAdminActiveDirectoryRoute
  '/_authenticated/briefings/$id': typeof AuthenticatedBriefingsIdRoute
  '/_authenticated/briefings/': typeof AuthenticatedBriefingsIndexRoute
  '/api/public/hooks/pm-reminders': typeof ApiPublicHooksPmRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/activity'
    | '/assets'
    | '/dashboard'
    | '/network'
    | '/pm'
    | '/reports'
    | '/servers'
    | '/software'
    | '/tech'
    | '/tickets'
    | '/admin/active-directory'
    | '/briefings/$id'
    | '/briefings/'
    | '/api/public/hooks/pm-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/activity'
    | '/assets'
    | '/dashboard'
    | '/network'
    | '/pm'
    | '/reports'
    | '/servers'
    | '/software'
    | '/tech'
    | '/tickets'
    | '/admin/active-directory'
    | '/briefings/$id'
    | '/briefings'
    | '/api/public/hooks/pm-reminders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/activity'
    | '/_authenticated/assets'
    | '/_authenticated/dashboard'
    | '/_authenticated/network'
    | '/_authenticated/pm'
    | '/_authenticated/reports'
    | '/_authenticated/servers'
    | '/_authenticated/software'
    | '/_authenticated/tech'
    | '/_authenticated/tickets'
    | '/_authenticated/admin/active-directory'
    | '/_authenticated/briefings/$id'
    | '/_authenticated/briefings/'
    | '/api/public/hooks/pm-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksPmRemindersRoute: typeof ApiPublicHooksPmRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tickets': {
      id: '/_authenticated/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthenticatedTicketsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tech': {
      id: '/_authenticated/tech'
      path: '/tech'
      fullPath: '/tech'
      preLoaderRoute: typeof AuthenticatedTechRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/software': {
      id: '/_authenticated/software'
      path: '/software'
      fullPath: '/software'
      preLoaderRoute: typeof AuthenticatedSoftwareRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/servers': {
      id: '/_authenticated/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof AuthenticatedServersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pm': {
      id: '/_authenticated/pm'
      path: '/pm'
      fullPath: '/pm'
      preLoaderRoute: typeof AuthenticatedPmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/network': {
      id: '/_authenticated/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof AuthenticatedNetworkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assets': {
      id: '/_authenticated/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AuthenticatedAssetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/briefings/': {
      id: '/_authenticated/briefings/'
      path: '/briefings'
      fullPath: '/briefings/'
      preLoaderRoute: typeof AuthenticatedBriefingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/briefings/$id': {
      id: '/_authenticated/briefings/$id'
      path: '/briefings/$id'
      fullPath: '/briefings/$id'
      preLoaderRoute: typeof AuthenticatedBriefingsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/active-directory': {
      id: '/_authenticated/admin/active-directory'
      path: '/admin/active-directory'
      fullPath: '/admin/active-directory'
      preLoaderRoute: typeof AuthenticatedAdminActiveDirectoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/pm-reminders': {
      id: '/api/public/hooks/pm-reminders'
      path: '/api/public/hooks/pm-reminders'
      fullPath: '/api/public/hooks/pm-reminders'
      preLoaderRoute: typeof ApiPublicHooksPmRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedAssetsRoute: typeof AuthenticatedAssetsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNetworkRoute: typeof AuthenticatedNetworkRoute
  AuthenticatedPmRoute: typeof AuthenticatedPmRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedServersRoute: typeof AuthenticatedServersRoute
  AuthenticatedSoftwareRoute: typeof AuthenticatedSoftwareRoute
  AuthenticatedTechRoute: typeof AuthenticatedTechRoute
  AuthenticatedTicketsRoute: typeof AuthenticatedTicketsRoute
  AuthenticatedAdminActiveDirectoryRoute: typeof AuthenticatedAdminActiveDirectoryRoute
  AuthenticatedBriefingsIdRoute: typeof AuthenticatedBriefingsIdRoute
  AuthenticatedBriefingsIndexRoute: typeof AuthenticatedBriefingsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedAssetsRoute: AuthenticatedAssetsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNetworkRoute: AuthenticatedNetworkRoute,
  AuthenticatedPmRoute: AuthenticatedPmRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedServersRoute: AuthenticatedServersRoute,
  AuthenticatedSoftwareRoute: AuthenticatedSoftwareRoute,
  AuthenticatedTechRoute: AuthenticatedTechRoute,
  AuthenticatedTicketsRoute: AuthenticatedTicketsRoute,
  AuthenticatedAdminActiveDirectoryRoute:
    AuthenticatedAdminActiveDirectoryRoute,
  AuthenticatedBriefingsIdRoute: AuthenticatedBriefingsIdRoute,
  AuthenticatedBriefingsIndexRoute: AuthenticatedBriefingsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksPmRemindersRoute: ApiPublicHooksPmRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
